milo_fcx/Cotizador/urls.py
from django.urls import path
from. import views

urlpatterns = [
   path('Cotizador/', views.cotizador, name='cotizador'),
    
]

milo_fcx/milo/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.Inicio, name='Inicio'),
    
]

milo_fcx/milo_fcx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('milo.urls')),
    path('',include ('register_login.urls')),
    path('',include ('Cotizador.urls')),
    path('',include ('tickets.urls')),
]

milo_fcx/register_login/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('Registrar/', views.User_Register, name='User_Register'),
   path('Login/', views.user_login, name='login'),
   path("logout/", views.user_logout, name='logout'),
    
]

milo_fcx/tickets/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('Tickets/', views.tickets, name='tickets'),

]

milo_fcx/Cotizador/models.py
from django.db import models

# Create your models here.

milo_fcx/milo/models.py
from django.db import models

# Create your models here.

milo_fcx/register_login/models.py
from django.db import models

# Create your models here.

milo_fcx/tickets/models.py
from django.db import models
from users.models import User
# Create your models here.

class Ticket(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    correo = models.CharField(max_length=100)
    empresa = models.CharField(max_length=100)
    referencia = models.CharField(max_length=100)
    serial = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    garantia = models.CharField(max_length=100)
    fuente = models.BooleanField(default=False)
    hdd = models.BooleanField(default=False)
    cables = models.BooleanField(default=False)
    caja = models.BooleanField(default=False)
    defectoDelEquipo = models.TextField(max_length=2000)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    img1 = models.ImageField(upload_to='tickets/img/', blank=True)
    img2 = models.ImageField(upload_to='tickets/img/', blank=True)
    img3 = models.ImageField(upload_to='tickets/img/', blank=True)
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name
    
    
    class meta:
        pass

milo_fcx/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
# Create your models here.

class User(AbstractUser):
    id = models.AutoField(primary_key=True)
    celular_cli = models.CharField(max_length=100, blank=True)
    Nit_cli = models.CharField(max_length=100, blank=True)
    
    

milo_fcx/register_login/forms.py
from django import forms
from users.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'celular_cli', 'Nit_cli', 'password1', 'password2']

milo_fcx/tickets/forms.py
from django import forms
from .models import Ticket



class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('name', 'correo', 'empresa','referencia','serial','marca', 'garantia', 'fuente', 'hdd', 'cables', 'caja', 'img1', 'img2', 'img3')

milo_fcx/Cotizador/views.py
from django.shortcuts import render

# Create your views here.

def cotizador(request):
    return render(request, 'cotizador.html')

milo_fcx/milo/views.py
from django.shortcuts import render 


# Create your views here.

def Inicio(request):
    return render(request, ('Inicio.html'))

milo_fcx/register_login/views.py
from django.db import IntegrityError
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .forms import UserRegisterForm
from users.models import User
# Create your views here.

def User_Register(request):
    if request.method == 'GET':
        return render(request, 'registro_user.html',{
            'form' : UserRegisterForm()
        })
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'], email=request.POST['email'], celular_cli=request.POST['celular_cli'], Nit_cli=request.POST['Nit_cli'])
                user.save()
                login(request, user)
                return render(request, 'registro_user.html', {
                        'form': UserRegisterForm(),
                        'error': 'registrado correctamente'
                    })  
            except IntegrityError:
                    return render(request, 'registro_user.html', {
                        'form': UserRegisterForm(),
                        'error': 'usurario ya existe'
                    })   
        return render(request, 'registro_user.html',{
            'form': UserRegisterForm(),
            'error': 'contrasena no coinciden'
            }) 

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('Inicio')  # Cambia 'home' por el nombre de tu vista de inicio
            else:
                error_message = "Credenciales inválidas. Por favor, inténtelo de nuevo."
                return render(request, 'login.html', {'form': form, 'error_message': error_message})
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('Inicio')

milo_fcx/tickets/views.py
from django.shortcuts import render
from.models import Ticket

# Create your views here.
def tickets(request):

    tickets = Ticket.objects.all()
    return render(request, 'tickets.html',{
        'tickets': tickets
    })

milo_fcx/users/views.py
from django.shortcuts import render

# Create your views here.

milo_fcx/milo/templates/Inicio.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Fenix Comercial {% endblock %}

{% block css  %}
<link rel="stylesheet" href="{% static 'css/inicio.css'  %}">
{% endblock %}
{% block content %}
    <div class="slide-container">
        <div class="slider-content">
            <div class="card-wrapper">
                <div class="card">
                    <div class="image-content">
                        <span class="overlay"></span>
                        <div class="card-image">
                            <img src="" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block js %}
<script src="{% static 'js/inicio.js' %}"></script>
{% endblock %}

milo_fcx/milo/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/Fenix.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css %}
    {% endblock %}
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="sidebar close">
        <header>
            <div class="imagen-text">
                <span class="imagen">
                    <img src="{% static 'img/Fenix.png' %}" alt="My image">
                </span>
                <div class="text header-text">
                    <span class="name">Fenix  Comercial</span>
                </div>
            </div>
            <i class="bx bx-chevron-right toggle"></i>
        </header>
        <div class="menu-bar">
            <div class="menu">
                <ul class="menu-links">
                    <li class="search-box">
                        <a href="#">
                            <i class='bx bx-search-alt-2 icon ' ></i>
                            <input type="search" placeholder="Buscar....">
                        </a>
                    </li>
                    <li class="nav-links">
                        <a href="{% url 'Inicio' %}">
                            <i class='bx bx-home  icon'></i>
                            <span class="text nav-text"> Inicio</span>
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-links">
                        <a href="{% url 'cotizador' %}">
                            <i class='bx bxs-hard-hat  icon'></i>
                            <span class="text nav-text">Cotizaciones</span>
                        </a>
                    </li>
                    <li class="nav-links">
                        <a href="{% url 'tickets' %}">
                            <i class='bx bxs-add-to-queue icon' ></i>
                            <span class="text nav-text">Tickets</span>
                        </a>
                    </li>
                    {% endif %}

                    <li class="nav-links">
                        <a href="#">
                            <i class='bx bxs-info-circle  icon' ></i>
                            <span class="text nav-text">Nosotros</span>
                        </a>
                    </li>
                </ul>
        </div>
        <div class="botton-content">
            {% if user.is_authenticated %}
            <li class="">
                <a href="{% url 'logout' %}">
                    <i class='bx bx-log-out icon'></i>
                    <span class="text nav-text">serrar sesion</span>
                </a>
            </li>
            {% else %}
            <li class="">
                <a href="{% url 'login' %}">
                    <i class='bx bx-log-in icon' ></i>
                    <span class="text nav-text">Iniciar</span>
                </a>
            </li>
            {% endif %}
            <li class="mode">
                <div class="moon-sun">
                    <i class="bx bx-moon monn icon"></i>
                    <i class="bx bx-sun sun icon"></i>
                </div>
                <span class="moden-text text">Dark Mode</span>

                <div class="toggle-switch">
                <span class="switch"></span>
                </div>
                </li>
            </div>
    </div>
    </nav>
    <div class="contenido">
        <div class="text">
            <center>
                {% block content %}
            
                {% endblock %}
            </center>
        </div>
    </div>
    {% block js %}
    {% endblock %}

    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>

milo_fcx/milo/templates/cotizador.html
{% extends 'base.html' %}
{% block title %} Cotizacion {% endblock %}
{% load static %}
{% block css  %}
    <link rel="stylesheet" href="{% static 'css/'  %}">
    {% endblock %}
        {% block content %}

        <form>
            
        </form>

        {% endblock %}
    {% block js %}
    <script src="{% static 'js/.js' %}"></script>
    {% endblock %}

milo_fcx/milo/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block css  %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block title %} Inisia Sesión {% endblock %}

{% block content %}
{{error}}
<section>
  <div class="contenedor">
    <div class="formulario">
      <form method="POST">
        {% csrf_token %}
        <h2 >Inicia Sesión</h2>
        <div class="input_contenedor">
          <i class='bx bx-envelope'></i>
          <input type="text" name="username" required>
          <label for="id_username">Nombre</label>
        </div>
        <div class="input_contenedor">
          <i class='bx bxs-lock-open'></i>
          <input type="password" name="password" required>
          <label for="id_password">Contraseña</label>
        </div>
        <div class="olvidar">
          <label for="#">
            <input type="checkbox">
            <a href="#">Recordar contraseña</a>
          </label>
        </div>
        <button>Acceder</button>
      </form>
      <div>
      
      </div>
    </div>
  </div>
</section>

{% endblock %}

milo_fcx/milo/templates/registro_user.html
{% extends 'base.html' %}
{% load static %}
{% block css  %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}
{% block title %} Registro de usuarios {% endblock %}
{% block content %}
  
{{error}}
<section>
    <div class="contenedor">
      <div class="formulario">
        <form method="POST" >
            {% csrf_token %}
          <h2>Registro</h2>
          <div class="input_contenedor">
            <i class='bx bxs-user' ></i>
            <input type="text" name="username" id="username" required>
            <label for="id_username">Nombre</label>
          </div>
          <div class="input_contenedor">
            <i class='bx bx-envelope'></i>
            <input type="email" name="email" id="email" required>
            <label for="id_email">Correo</label>
          </div>
          <div class="input_contenedor">
            <i class='bx bx-mobile'></i>
            <input type="text" name="celular_cli" id="celular_cli" required>
            <label for="id_celular_cli">Celular</label>
          </div>
          <div class="input_contenedor">
            <i class='bx bxs-wallet'></i>
            <input type="text" name="Nit_cli" id="Nit_cli">
            <label for="id_Nit_cli">Nit</label>
          </div>
          <div class="input_contenedor">
            <i class='bx bxs-lock-open'></i>
            <input type="password" autocomplete="new-password" name="password1" id="password1" required>
            <label for="id_password1">contraseña</label>
        </div>
        <div class="input_contenedor">
            <i class='bx bxs-lock-open'></i>
            <input type="password" autocomplete="new-password" name="password2" id="password2" required>
            <label for="id_password2">validar contraseña</label>
        </div>
            <div>
            <button>Acceder</button>
          </div>
        </form>

      </div>
    </div>
  </section>
{% endblock %}

milo_fcx/milo/templates/tickets.html
{% extends 'base.html' %}
{% block title %} Tickets Garantia {% endblock %}
{% load static %}
{% block css  %}
    <link rel="stylesheet" href="{% static 'css/tickest.css'  %}">
{% endblock %}
        {% block content %}
        
            <div class="container">
                <div class="title">
                    <h1>Tickets Garantia</h1>
                    <form method="POST" >
                        {% csrf_token %}
                        <div class="user-details">
                            <div class="imput-box">
                                <span class="details">Nombre</span>
                                <input type="text" placeholder="cliente" name="name" required>
                            </div>
                            <div class="imput-box">
                                <span class="details">Correo</span>
                                <input type="email" placeholder="Correo" name="correo" required>
                            </div>
                            <div class="imput-box">
                                <span class="details">Empresa</span>
                                <input type="text" placeholder="Empresa" name="empresa" >
                            </div>
                            <div class="imput-box">
                                <span class="details">Referencia</span>
                                <input type="text" placeholder="Refereencia" name="referencia" required>
                            </div>
                            <div class="imput-box">
                                <span class="details">Serial</span>
                                <input type="text" placeholder="Serial" name="serial" required>
                            </div>
                            <div class="imput-box">
                                <span class="details">Marca</span>
                                <select name=" marca">
                                    <option value="..." selected>...</option>
                                    <option value="Hikvision">Hikvision</option>
                                    <option value="Hilook" >Hilook</option>
                                    <option value="Reyee">Reyee</option> 
                                    <option value="Otra">Otra</option> 
                                  </select>
                            </div>
                            <div class="imput-box">
                                <span class="details">Garantia</span>
                                <select name="garantia">
                                    <option value="..." selected>...</option>
                                    <option value="Hikvision">Hikvision</option>
                                    <option value="Fenix" >Fenix</option>
                                    <option value="Fuera de Garantia" >Fuera de Garantia </option>
                                  </select>
                            </div>
                            <div class="imput-box">
                                <span class="details">Sintoma del equipo</span>
                                <input type="text" placeholder="No inicia, no da video ETC..." name="defectoDelEquipo" required>
                            </div>
                            <div class="imput-box img-foto">
                                <span class="details">Subir foto del stiker </span>
                                <input type="file" name="foto_estiker" >
                            </div>
                            <div class="imput-box img-foto">
                                <span class="details">Subir foto del equipo</span>
                                <input type="file" name="foto_estiker" >
                            </div>
                            <div class="imput-box img-foto">
                                <span class="details">Subir Foto de la falla</span>
                                <input type="file" name="foto_estiker" >
                            </div>                           
                            <div class="checkbox ">
                                <span class="details">Accesorios:</span>
                                <label for="Adaptador de corriente">Fuente</label>
                                <input type="checkbox" id="Adaptador_de_corriente" name="Adaptador de corriente" value="Adaptador_de_corriente">
                                <label for="HDD">HDD</label>
                                <input type="checkbox" id="HDD" name="HDD" value="HDD">
                                <label for="Cables">Cables</label>
                                <input type="checkbox" id="Cables" name="Cables" value="Cables">
                                <label for="Caja">Caja</label>
                                <input type="checkbox" id="Caja" name="Caja" value="Caja">
                            </div>
                            <input class="button" type="submit" value="Crear tiket">
                    </form>
                    <div class="date">
                        <table>
                            <th>N°Tickets</th>
                            <th>Nombre</th>
                            <th>Correo</th>
                            <th>Empresa</th>
                            <th>Referencia</th>
                            <th>Serial</th>
                            <th>Marca</th>
                            <th>Garantia</th>
                            <th>Sintoma del equipo</th>
                            <th>info....</th>
                            {% for ticket in tickets %}
                            <tr>
                                <td>{{ticket.id}}</td>
                                <td>{{ticket.name}}</td>
                                <td>{{ticket.correo}}</td>
                                <td>{{ticket.empresa}}</td>
                                <td>{{ticket.referencia}}</td>
                                <td>{{ticket.serial}}</td>
                                <td>{{ticket.marca}}</td>
                                <td>{{ticket.garantia}}</td>
                                <td>{{ticket.defectoDelEquipo}}</td>
                            </tr>
                            {% endfor %}      
                        </table> 
                    </div>
                </div>
            </div>
        
        {% endblock %}
    {% block js %}
    <script src="{% static 'js/Tikets.js' %}"></script>
    {% endblock %}